### ISSUE TITLE
 error: Initialization error -  Cannot read property 'brunchPluginName' of null

### ISSUE THREAD

**Issue by abidi** [tulinmola/kafka-dashboards#1]
Hi,
When I try to build the docker image I got this error : 
`Step 13/16 : RUN LOGGY_STACKS=true NODE_ENV=production node_modules/brunch/bin/brunch build --production
 ---> Running in 6fd8d209a7d9
26 May 16:24:54 - error: Initialization error -  Cannot read property 'brunchPluginName' of null 
Type  at /app/node_modules/brunch/lib/plugins.js:140:33
  at Array.filter (native)
  at Object.packages.filter.plugins.map.plugin.filter.prop.filter.slice.call.map.uniqueDeps.map.exports.init.plugins.filter.map.preCompilers.push.teardownBrunch [as init] (/app/node_modules/brunch/lib/plugins.js:139:38)
  at /app/node_modules/brunch/lib/watch.js:110:19
  at process._tickCallback (internal/process/next_tick.js:103:7)`
I added LOGGY_STACKS=true to display debug message

**Comment by tulinmola** [comment]
Hello Abdelaziz, it looks like being a problem with modern versions of Brunch. There is an [solved issue](https://github.com/brunch/sass-brunch/issues/107) in [brunch-sass](https://github.com/brunch/sass-brunch) repo. Keep in mind I haven't touched this project in 4 years… If you manage to solve it with that issue information, please make a PR. Maybe it could be worth to someone else in your situation. Cheers!
